tools:
  - stringtie
  - talon

species:
  - human
  - mouse

platforms:
  - ONT
  - PacBio

lrgasp:
  dir: data/raw/lrgasp

  reference:
    human:
      fasta: data/raw/lrgasp/references/lrgasp_grch38_sirvs.fasta
      gtf: data/raw/lrgasp/references/lrgasp_gencode_v38_sirvs.gtf
    mouse:
      fasta: data/raw/lrgasp/references/lrgasp_grcm39_sirvs.fasta
      gtf: data/raw/lrgasp/references/lrgasp_gencode_vM27_sirvs.gtf
    manatee:
      fasta: data/raw/lrgasp/references/lrgasp_manatee_sirv1.fasta
    sirv:
      fasta: data/raw/lrgasp/references/lrgasp_sirv4.fasta
      gtf: data/raw/lrgasp/references/lrgasp_sirvs4.gtf

  simulation:
    illumina_fq1: data/raw/lrgasp/simulation/{specie}_simulation/{specie}.Illumina.simulated_1.fq
    illumina_fq2: data/raw/lrgasp/simulation/{specie}_simulation/{specie}.Illumina.simulated_2.fq
    ONT: data/raw/lrgasp/simulation/{specie}_simulation/{specie}.ONT.simulated.fq
    PacBio: data/raw/lrgasp/simulation/{specie}_simulation/{specie}.PacBio.simulated.fasta

utilities:
  dir: data/raw/utilities/
  polyA_list: data/raw/utilities/polyA_list.txt
  tss: data/raw/utilities/refTSS.{specie}.bed
      
star:
  index: data/processed/{specie}_star_index/
  bam: data/processed/{specie}_illumina/Aligned.sortedByCoord.out.bam
  SJ: data/processed/{specie}_illumina/SJ.out.tab

minimap:
  sam: data/processed/{specie}_minimap/{platform}/simulated_{specie}_{platform}.sam
  bam: data/processed/{specie}_minimap/{platform}/simulated_{specie}_{platform}.bam
      
talon:
  samples: configs/talon_{specie}_sample_config.csv
  config:
    annot_name: lrgasp_annot
    genome_name: lrgasp_genome
    dist_5p: 500
    dist_3p: 300
    min_transcript_length: 0
    idprefix: lrgasp

  tmp_dir: data/processed/_talon_tmp/
  sam_read_ann: data/processed/talon/{specie}/{platform}/simulated_{specie}_{platform}_labeled.sam
  db: data/processed/talon/{specie}/{specie}_lrgasp.db
  read_annot: data/processed/talon/{specie}/talon_output/{specie}_talon_read_annot.tsv
  
  white_list: data/processed/talon/{specie}/{specie}_pass_list.csv
  gtf: data/processed/talon/{specie}/{platform}/simulated_{specie}_{platform}_talon.gtf
  
stringtie:
  gtf_raw: data/processed/stringtie/{specie}/{platform}/simulated_{specie}_{platform}_stringtie_raw.gtf
  gtf: data/processed/stringtie/{specie}/{platform}/simulated_{specie}_{platform}_stringtie.gtf

tools:
  gtf: data/processed/{tool}/{specie}/{platform}/simulated_{specie}_{platform}_{tool}.gtf

cupcake_path: /data/homezvol2/mcelik/Projects/cDNA_Cupcake/
sqanti3_lrgasp_path: /data/homezvol2/mcelik/Projects/lrgasp-submissions/bin/sqanti3_evaluation/sqanti3_lrgasp.py


benchmark:
  result_dir: data/processed/results/{tool}/{specie}_{platform}/
