tmpdir: /pub/mcelik/tmp/

tools:
  - talon
  # - stringtie

species:
  - human
  # - mouse

platforms:
  - PacBio
  # - ONT

cell_lines:
  - WTC11
  # - H1mix
  # - ES

library_prep:
  - cDNA
  # - CapTrap
  # - dRNA
  # - R2C2
  
lrgasp:
  dir: data/raw/lrgasp

  reference:
    human:
      fasta: data/raw/lrgasp/references/lrgasp_grch38_sirvs.fasta
      gtf: data/raw/lrgasp/references/lrgasp_gencode_v38_sirvs.gtf
    mouse:
      fasta: data/raw/lrgasp/references/lrgasp_grcm39_sirvs.fasta
      gtf: data/raw/lrgasp/references/lrgasp_gencode_vM27_sirvs.gtf
    manatee:
      fasta: data/raw/lrgasp/references/lrgasp_manatee_sirv1.fasta
    sirv:
      fasta: data/raw/lrgasp/references/lrgasp_sirv4.fasta
      gtf: data/raw/lrgasp/references/lrgasp_sirvs4.gtf

  annotation_bed: data/raw/processed/common/{specie}_annotation.bed
      
  simulation:
    illumina_fq1: data/raw/lrgasp/simulation/{specie}_simulation/{specie}.Illumina.simulated_1.fq
    illumina_fq2: data/raw/lrgasp/simulation/{specie}_simulation/{specie}.Illumina.simulated_2.fq
    ONT: data/raw/lrgasp/simulation/{specie}_simulation/{specie}.ONT.simulated.fq
    PacBio: data/raw/lrgasp/simulation/{specie}_simulation/{specie}.PacBio.simulated.fasta

encode:
  data_matrix: data/raw/rnaseq-data-matrix.tsv
  raw_fastq: data/raw/encode/fastq/{encode_id}.{file_type}.gz
  fastq_dir: data/raw/encode/fastq
  fastq: data/raw/encode/fastq/{encode_id}.fastq

utilities:
  dir: data/raw/utilities/
  polyA_list: data/raw/utilities/polyA_list.txt
  tss: data/raw/utilities/refTSS.{specie}.bed
      
star:
  index: data/processed/star/{specie}_star_index/
  bam: data/processed/star/{specie}_{sample}_{platform}/Aligned.sortedByCoord.out.bam
  SJ: data/processed/star/{specie}_{sample}_{platform}/SJ.out.tab

minimap:
  sam: data/processed/minimap/{encode_id}.sam
  sam_sorted: data/processed/minimap/sorted/{encode_id}.sam
  bam: data/processed/minimap/{encode_id}.bam
  
transcriptclean:
  tc_path: ../TranscriptClean
  tc_tmpdir: /pub/mcelik/tmp_tc/{encode_id}_{method}_{batch_id}/
  sam: data/processed/transcriptclean/{encode_id}_{method}/{encode_id}_{method}_clean.sam

  batch_dir: data/processed/minimap/batch/{encode_id}/
  bam_batch: data/processed/minimap/batch/{encode_id}/shard_{batch_id}.bam
  sam_batch: data/processed/minimap/batch/{encode_id}/shard_{batch_id}.sam

  sam_clean_batch: data/processed/transcriptclean/{encode_id}_{method}/{encode_id}_{method}_batch/{batch_id}/shard_{batch_id}_clean.sam
  
  tmp_dir: data/processed/transcriptclean/{encode_id}_{method}/{encode_id}_{method}_tmp_dir
  fasta: data/processed/transcriptclean/{specie}.fasta
  gtf_sj: data/processed/transcriptclean/{specie}.SJ.out.tab
  
talon:
  samples: data/processed/talon/{specie}/{sample}/{platform}/{library_prep}/{specie}_{sample}_{library_prep}_{platform}_{method}_config.csv
  config:
    annot_name: "{specie}_{sample}_{library_prep}_{platform}_{method}"
    genome_name: lrgasp_genome
    dist_5p: 500
    dist_3p: 300
    min_transcript_length: 0
    idprefix: "{specie}_{sample}_{library_prep}_{platform}_{method}"
    
  tmp_dir_read_ann: /tmp/mcelik/read_ann/{encode_id}_{method}/talon_tmp
  sam_read_ann: data/processed/talon/{encode_id}_{method}/{encode_id}_{method}_labeled.sam

  db: data/processed/talon/{specie}/{sample}/{platform}/{method}/{specie}_{sample}_{library_prep}_{platform}_{method}.db
  
  tmp_dir: data/processed/talon/{specie}/{sample}/{platform}/{library_prep}/{method}/tmp_dir/  
  read_annot: data/processed/talon/{specie}/{sample}/{platform}/{library_prep}/{method}/{specie}_{sample}_{library_prep}_{platform}_{method}_talon_read_annot.tsv
  qc: data/processed/talon/{specie}/{sample}/{platform}/{library_prep}/{method}/{specie}_{sample}_{library_prep}_{platform}_{method}_QC.log

  white_list: data/processed/talon/{specie}/{sample}/{platform}/{library_prep}/{method}/{specie}_{sample}_{library_prep}_{platform}_{method}_pass_list.csv
  gtf: data/processed/talon/{specie}/{sample}/{platform}/{library_prep}/{method}/{specie}_{sample}_{library_prep}_{platform}_{method}_talon.gtf
  abundance: data/processed/talon/{specie}/{sample}/{platform}/{library_prep}/{method}/{specie}_{sample}_{library_prep}_{platform}_{method}_talon_abundance_filtered.tsv

stringtie:
  gtf_raw: data/processed/stringtie/{specie}/{platform}/simulated_{specie}_{platform}_stringtie_raw.gtf
  gtf: data/processed/stringtie/{specie}/{platform}/simulated_{specie}_{platform}_stringtie.gtf

tools:
  gtf: data/processed/{tool}/{specie}/{sample}/{platform}/{library_prep}/{method}/{specie}_{sample}_{library_prep}_{platform}_{method}_talon.gtf

cupcake_path: /data/homezvol2/mcelik/Projects/cDNA_Cupcake/
sqanti3_lrgasp_path: /data/homezvol2/mcelik/Projects/lrgasp-challenge-1-evaluation/sqanti3_lrgasp.challenge1.py

submission:
  task1:
    dir: data/processed/results/iso_detect_ref_{tool}_{method}/
    entry: data/processed/results/iso_detect_ref_{tool}_{method}/entry.json
    experiment: data/processed/results/iso_detect_ref_{tool}_{method}/{specie}_{sample}_{library_prep}_{platform}/experiment.json

  task2:
    dir: data/processed/results/iso_quant_{tool}_{method}/
    entry: data/processed/results/iso_quant_{tool}_{method}/entry.json
    experiment: data/processed/results/iso_quant_{tool}_{method}/{specie}_{sample}_{library_prep}_{platform}/experiment.json
    expression: data/processed/results/iso_quant_{tool}_{method}/{specie}_{sample}_{library_prep}_{platform}/expression.tsv
    
benchmark_task1:
  result_dir: data/processed/results/task1/{tool}/{method}/{specie}_{sample}_{library_prep}_{platform}/

  
benchmark_task2:
  path: /data/homezvol2/mcelik/Projects/lrgasp-challenge-2-evaluation/encode_quantification/main.py
  result_dir: data/processed/results/task2/{tool}/{method}/{specie}_{sample}_{library_prep}_{platform}/

